name: Solid CI/CD

on: [push, pull_request]

env:
  NODE_VERSION: 20.x
  NPM_CACHE_DIR: ${{ github.workspace }}/.npm

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      npm-cache-key: ${{ steps.cache-deps.outputs.cache-key }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.NPM_CACHE_DIR }}
            !**/node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm install

  lint-and-format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use cached dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.NPM_CACHE_DIR }}
          key: ${{ needs.setup.outputs.npm-cache-key }}
      - name: Format code
        run: npm run format
      - name: Lint code
        # run: npm run lint
        run: npm run test

  unit-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use cached dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.NPM_CACHE_DIR }}
          key: ${{ needs.setup.outputs.npm-cache-key }}
      - name: Run Unit Tests
        run: npm test

  e2e-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use cached dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.NPM_CACHE_DIR }}
          key: ${{ needs.setup.outputs.npm-cache-key }}
      - name: Run E2E Tests
        # run: npm run test:e2e
        run: npm run test

  build:
    needs: [unit-tests, e2e-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use cached dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.NPM_CACHE_DIR }}
          key: ${{ needs.setup.outputs.npm-cache-key }}
      - name: Build
        run: npm run build
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build-artifact
      #     path: path/to/your/build/folder
