name: React CI/CD

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm ci
    - name: Format code
      run: npm run format
    - name: Lint code
      run: npm run lint
    - name: Run Unit Tests
      run: npm test
    - name: Run E2E Tests
      run: npm run test:e2e
    - name: Build
      run: npm run build
